include:
  - project: 'ihp/julia/julia-gitlab-ci-templates'
    ref: v1.1.0
    file: '/.gitlab-ci_template.yaml'

build_container:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --no-push

.install_pylon:
  before_script:
    - source src/install_pylon.sh

build:1.6:
  stage: build
  extends:
    - .julia:1.6
    - .install_pylon
  script:
    - bash src/build.sh
  artifacts:
    paths:
      - build/lib/libpylon_julia_wrapper.so

test:1.3:
  needs:
    - build:1.6
  extends:
    - .julia:1.3
    - .install_pylon
    - .julia.test.basic

test:1.6:
  needs:
    - build:1.6
  extends:
    - .julia:1.6
    - .install_pylon
    - .julia.test
