name = "PylonWrapper"
uuid = "36ec52b6-4a64-11e9-0b08-d9a7b99daa16"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
CxxWrap = "0.11.2"
julia = "1.3"
